### ISSUE TITLE
Copying teapot example (licensing)

### ISSUE THREAD

**Issue by yazgoo** [zesterer/euc#11]
Hi,

Thanks for this awesome crate.

In my new project, I've written an example using code from this repository.
I've also used teapod.obj and teapot.mtl.

See https://github.com/yazgoo/blockish/tree/master/examples

Is there any restriction to using these ?
Any license that should be used particularly ?

Thanks !

BTW here is a the example running https://www.youtube.com/watch?v=eI5IS7rz9WI

**Comment by zesterer** [comment]
Hello!

The teapot in question is the "Utah Teapot" - an infamous graphics test model. I'm not aware of any specific license covering its use, but don't quote me on that. Regardless, it's so frequently used that you're incredibly unlikely to run into legal trouble even if there does exist a license that is not permissive.

**Comment by yazgoo** [comment]
Thanks !
