### ISSUE TITLE
Sampler does not work with the latest version of image

### ISSUE THREAD

**Issue by markusmoenig** [zesterer/euc#27]
The sampler does not work with the latest version of the image crate (0.24.*).

Something about the trait bonds not being satisfied.

**Comment by zesterer** [comment]
This will be because cargo is compiling in two versions of the same crate (0.23, which `euc` depends on, and 0.24, which you depend on).

I've pushed up [a commit](994b1dd) that should resolve this.

**Comment by markusmoenig** [comment]
Yes, thanks, that fixes it, texture_packer was also on a different version and it got all scrambled up.
