### ISSUE TITLE
Latest version on crates.io

### ISSUE THREAD

**Issue by markusmoenig** [zesterer/euc#32]
Hi,

Question, the latest version is not on crates.io right ? Because the latest version there is over 3 years old.

Thanks.

**Comment by zesterer** [comment]
Not yet. The latest `master` is really very close to a release, but I've not had time to finish off a few corners of the docs, among other things. Were you looking to use it?

**Comment by markusmoenig** [comment]
@zesterer Yeah, I did a lot of tests recently and decided to rewrite my https://github.com/markusmoenig/Eldiron project to use euc both for 2D and 3D rendering for my new Doom-style editor. For my low-poly approach it is more than sufficient and it has some cool side effects, for example being able to render procedural materials on the fly on the CPU.

I will link in the latest version from GitHub than until it is on crates.io. Thanks a lot, love euc.

**Comment by zesterer** [comment]
Oh, very cool! I'm happy to hear you're enjoying using `euc`. Is getting the latest version released as stable your primary bottleneck, or are there more features you'd like to see?

**Comment by markusmoenig** [comment]
The main thing is that it is supported .... . Up until now I only tested performance on some devices, I am just now starting implementing stuff. Guess will have some questions down the line.

Thanks again for your work.

**Comment by markusmoenig** [comment]
@zesterer Ah, I did not realize you do not have a TriangleStrip / TriangleFan primitive, that is unfortunate. Will need to implement this on my side to rasterize polygons.

**Comment by markusmoenig** [comment]
@zesterer 

In the red 2D box I get, a visible split between the two polygons depending on the aspect ratio of the window. During resizing some aspect ratios work, some do not. Is that expected behavior ?

<img width="1342" alt="Screenshot 2024-11-27 at 19 17 39" src="https://github.com/user-attachments/assets/816d413b-a29d-445a-a416-9723f76c3aa0">

**Comment by zesterer** [comment]
It's not intended, I suspect this is a fill convention issue. I can take a look at this soon.

**Comment by zesterer** [comment]
Additionally, `TriangleStrip`/`TriangleFan` should be fairly easy to implement upon the existing primitive API.

**Comment by markusmoenig** [comment]
Don't worry about the TriangleStrip, I earcut my sectors / polygon anyway.

**Comment by markusmoenig** [comment]
@zesterer Sorry for all the messages :)

1. Is it possible to support transparent sampler output, i.e. skipping that triangle when the sampler returns an alpha of 0.0 at that location ? For gates / windows ?

2. What I did not take into consideration is that I want to repeat / tile the textures per unit (like in Doom), meaning that I have to draw every geometry for every texture separately, meaning there are many draw calls which prevent the multi-threading to fully kick in I guess.
