### ISSUE TITLE
Euc clipping triangles under the camera ?

### ISSUE THREAD

**Issue by markusmoenig** [zesterer/euc#33]
Hi,

is it possible that Euc is clipping triangles under the camera ? See attached images. CullMode is None. In the first image the camera is in front of the sector, in the second I moved the camera forward and it is on top of first geometry which gets clipped.

<img width="1312" alt="Screenshot 2024-12-04 at 18 55 48" src="https://github.com/user-attachments/assets/ef670365-a091-475e-8562-f7a2fbc2459f">
<img width="1312" alt="Screenshot 2024-12-04 at 18 55 56" src="https://github.com/user-attachments/assets/21be0659-7aab-4652-912d-9d750d749a19">

**Comment by zesterer** [comment]
I can check this over the weekend, but I suspect that it's not properly clipping against the near plane.

**Comment by markusmoenig** [comment]
Did you have time to look at it ? I mean without this being fixed I do not need to continue integration.

**Comment by zesterer** [comment]
Sorry, I've not had time. Do you have instructions for something I can run to observe this? If it's too complex, that's fine.

**Comment by markusmoenig** [comment]
Sorry in the meantime I wrote the basics of my own renderer, see https://github.com/markusmoenig/Rusterix.

I just have a very specific use case and it did not make sense to try to fit euc into that. I use a tile based renderer which precomputes the bounding boxes and edges of batches during projection.

I think it is a bit faster (but also not yet full featured lol).

**Comment by zesterer** [comment]
Very cool! Sorry that Euc turned out to not be a good fit for you, but I'm glad you've found a solution.
