### ISSUE TITLE
Use perspective correct interpolation

### ISSUE THREAD

**Issue by MartinSandfuchs** [zesterer/euc#5]
At the moment the vertex attributes are interpolated linearly in screen space which produces an incorrect result. This is especially visible when using interpolated texture coordinates (see image below).
![image](https://user-images.githubusercontent.com/16427752/57196757-2502e100-6f60-11e9-8620-2902defc575a.png)
Fixing this issue probably requires the vertex shader to output a 4d vector in homogeneous coordinates. The w component of the vector can then be used by the rasterizer to perform perspective correct interpolation (this is how I believe OpenGL does it).

**Comment by zesterer** [comment]
I'll look into adding this in the near future. Is this something you're needing to have working soon?

**Comment by MartinSandfuchs** [comment]
I don't need to have it working any time soon. Just thought it would be a neat feature to have.
