### ISSUE TITLE
texture mapping?

### ISSUE THREAD

**Issue by wez** [zesterer/euc#6]
It looks like `texture.rs` isn't complete and isn't included in the build at the moment; do you have a rough ETA on when texture mapping will be ready to try out?  Or if I've missed something, could you give a quick example of how it works?

My use case is pretty simple: I'm currently using the GPU to place and color glyphs rendered by eg: freetype in a terminal application.  In some situations (eg: remote desktop, or remote X11 server), the [GPU isn't available ](https://github.com/wez/wezterm/issues/40) so I'd like to fall back to a software renderer.  I'm interested in the idea of a simple layer (that will live in my application) that sits over the top of eg: `euc` and `opengl` so I can avoid having wildly diverging render paths.

**Comment by zesterer** [comment]
Hi, thanks for contacting me.

Texture support has been in the works for a while. What is your particular use case? You might be better off directly sampling a type from the `image` crate in Euc's fragment shader.

**Comment by zesterer** [comment]
This has now been implemented.
